export { default as HeaderBackground } from './background.svg';
export { default as LeftFlowerIcon } from './left-flower.svg';
export { default as RightFlowerIcon } from './right-flower.svg';
export { default as TitleIcon } from './title.svg';
export { default as FacebookIcon } from './facebook.svg';
export { default as InstagramIcon } from './instagram.svg';
export { default as YoutubeIcon } from './youtube.svg';
export { default as MailIcon } from './mail.svg';
export { default as FooterFlowerIcon } from './footer-flower.svg';
